version: "3"
services:
  brokerage:
    build: ./brokerage
    ports:
      - "8000:8000"
    networks:
      - broknet
      - exnet
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - exchange
  exchange:
    build: ./exchange
    ports:
      - "5000:5000"
    networks:
      - broknet
      - exnet
    command: python exchange.py
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - exnet
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - exnet
networks:
  broknet:
  exnet:
