# Generated by Django 2.0.2 on 2018-02-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180216_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='trades',
            field=models.ManyToManyField(blank=True, null=True, to='api.Trade'),
        ),
    ]
