# Generated by Django 2.0.2 on 2018-02-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_account_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=500, primary_key=True, serialize=False),
        ),
    ]
