# Generated by Django 2.0.2 on 2018-02-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180218_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='was_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='was_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='was_placed',
            field=models.BooleanField(default=False),
        ),
    ]
