# Generated by Django 2.0.2 on 2018-05-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buying_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying_order', to='api.Order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='selling_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selling_order', to='api.Order'),
        ),
    ]
