# Generated by Django 2.0.2 on 2018-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180517_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
