# Generated by Django 2.0.2 on 2018-05-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180517_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='was_cancelled',
        ),
    ]
