# Generated by Django 2.0.2 on 2018-05-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('api', '0014_remove_order_was_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
