# Generated by Django 2.0.2 on 2018-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trades',
            field=models.ManyToManyField(blank=True, to='api.Trade'),
        ),
    ]
